version: '3.8'
services:
  websocat:
    build:
      context: ./websocat
    network_mode: "host"
    restart: always

  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --url http://localhost:8022
    network_mode: "host"
    restart: always
    
