version: '3.8'
services:
  websocat:
    image: vi0oss/websocat:0.11.0
    network_mode: "host"
    restart: always
    command:
      - -E
      - --binary
      - ws-l:127.0.0.1:8022
      - tcp:127.0.0.1:22

  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --url http://localhost:8022
    network_mode: "host"
    restart: always
    
